# This file was generated by GoReleaser. DO NOT EDIT.
cask "mediainfo" do
  binary "mediainfo", target: "go-mediainfo"
  caveats <<~EOS
    If you already have Homebrew's MediaInfo installed, the `mediainfo` symlink may already exist.
    Use `go-mediainfo` to run this cask's binary.
  EOS

  name "mediainfo"
  desc "Go rewrite of MediaInfo CLI."
  homepage "https://github.com/autobrr/go-mediainfo"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mediainfo"

  on_macos do
    on_intel do
      url "https://github.com/autobrr/go-mediainfo/releases/download/v#{version}/mediainfo_#{version}_darwin_amd64.tar.gz"
      sha256 "f5e6165b6d0c1654db5d1bc5518f9c8abb9586c2e7b4eacc9e69a5de1689d247"
    end
    on_arm do
      url "https://github.com/autobrr/go-mediainfo/releases/download/v#{version}/mediainfo_#{version}_darwin_arm64.tar.gz"
      sha256 "b232807be3e2400493be58446d10e5b1d07bec8b02c12e14559a469a1c0a4dbb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/autobrr/go-mediainfo/releases/download/v#{version}/mediainfo_#{version}_linux_amd64.tar.gz"
      sha256 "06ae033e0ac785e386a49e781ab5fbaf623f7e660754f4794eeee1a2fa2f6b77"
    end
    on_arm do
      url "https://github.com/autobrr/go-mediainfo/releases/download/v#{version}/mediainfo_#{version}_linux_arm64.tar.gz"
      sha256 "2b5f5977eabaa000e0d9d765b3c9cd893dbe1d107fd7aeb4bc234c2bc4d83572"
    end
  end

  # No zap stanza required
end
