# This file was generated by GoReleaser. DO NOT EDIT.
cask "mediainfo" do
  binary "mediainfo", target: "go-mediainfo"
  caveats <<~EOS
    If you already have Homebrew's MediaInfo installed, the `mediainfo` symlink may already exist.
    Use `go-mediainfo` to run this cask's binary.
  EOS

  name "mediainfo"
  desc "Go rewrite of MediaInfo CLI."
  homepage "https://github.com/autobrr/go-mediainfo"
  version "0.1.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mediainfo"

  on_macos do
    on_intel do
      url "https://github.com/autobrr/go-mediainfo/releases/download/v#{version}/mediainfo_#{version}_darwin_amd64.tar.gz"
      sha256 "75462ab6b6a8fe8fd4e5a849bd6221f182436eb6c64cc704e5e74968d56f3254"
    end
    on_arm do
      url "https://github.com/autobrr/go-mediainfo/releases/download/v#{version}/mediainfo_#{version}_darwin_arm64.tar.gz"
      sha256 "12da63183d06ab6ce64772a65cfc0018e14a7db4a8a83dfd4baf9ae9cb7b5127"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/autobrr/go-mediainfo/releases/download/v#{version}/mediainfo_#{version}_linux_amd64.tar.gz"
      sha256 "2292b47290f7c0b6bf87cc2a50b1efc44dc72921f9a4975ed9e8db2e5c611442"
    end
    on_arm do
      url "https://github.com/autobrr/go-mediainfo/releases/download/v#{version}/mediainfo_#{version}_linux_arm64.tar.gz"
      sha256 "a0030203e8805cd3eaec7878c7db792a80d8d425b906ebf3da25802005823bd7"
    end
  end

  # No zap stanza required
end
