# This file was generated by GoReleaser. DO NOT EDIT.
cask "mediainfo" do
  name "mediainfo"
  desc "Go rewrite of MediaInfo CLI."
  homepage "https://github.com/autobrr/go-mediainfo"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mediainfo"
  binary "mediainfo", target: "go-mediainfo"

  caveats <<~EOS
    If you already have Homebrew's MediaInfo installed, the `mediainfo` symlink may already exist.
    Use `go-mediainfo` to run this cask's binary.
  EOS

  on_macos do
    on_intel do
      url "https://github.com/autobrr/go-mediainfo/releases/download/v#{version}/mediainfo_#{version}_darwin_amd64.tar.gz"
      sha256 "0c8e32ba6edfe6b0c16b1494e99e70feef951a53d58df46c13980b7dbc72e93b"
    end
    on_arm do
      url "https://github.com/autobrr/go-mediainfo/releases/download/v#{version}/mediainfo_#{version}_darwin_arm64.tar.gz"
      sha256 "cf4fcd2c4b86850c1890c37b28eedce1c725c6068d1be0b58e08256bd752e211"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/autobrr/go-mediainfo/releases/download/v#{version}/mediainfo_#{version}_linux_amd64.tar.gz"
      sha256 "9515dc59390b58226aa2142d82ee84c3c15e1837a4e8ede1038f3b08e81b7851"
    end
    on_arm do
      url "https://github.com/autobrr/go-mediainfo/releases/download/v#{version}/mediainfo_#{version}_linux_arm64.tar.gz"
      sha256 "8df10b52365f094bc45ef72d84ffaf1b0828192714b72e516fe2517f82d63a55"
    end
  end

  # No zap stanza required
end
