package mediainfo

var generalFieldOrder = map[string]int{
	"ID":                    -2,
	"Unique ID":             -1,
	"Complete name":         0,
	"CompleteName_Last":     0,
	"Format":                1,
	"Format/Info":           2,
	"Format settings":       3,
	"Format profile":        4,
	"Format version":        5,
	"Codec ID":              6,
	"File size":             7,
	"Duration":              8,
	"Overall bit rate mode": 9,
	"Overall bit rate":      10,
	"Frame rate":            11,
	"Writing application":   12,
	"Writing library":       13,
	"FileExtension_Invalid": 14,
	"Conformance warnings":  15,
	" General compliance":   16,
}

var streamFieldOrder = map[string]int{
	"ID":                                0,
	"Menu ID":                           1,
	"Format":                            2,
	"Format/Info":                       3,
	"Commercial name":                   4,
	"Format version":                    4,
	"Muxing mode":                       5,
	"Format profile":                    6,
	"HDR format":                        6,
	"Format settings":                   7,
	"Format settings, BVOP":             8,
	"Format settings, QPel":             9,
	"Format settings, GMC":              10,
	"Format settings, Matrix":           11,
	"Format settings, GOP":              12,
	"Format settings, CABAC":            13,
	"Format settings, Reference frames": 14,
	"Format settings, Slice count":      14,
	"Codec ID":                          15,
	"Codec ID/Info":                     16,
	"Duration":                          17,
	"Source duration":                   18,
	"Source_Duration_LastFrame":         19,
	"Bit rate mode":                     20,
	"Bit rate":                          21,
	"Nominal bit rate":                  22,
	"Maximum bit rate":                  23,
	"Width":                             24,
	"Height":                            25,
	"Display aspect ratio":              26,
	"Channel(s)":                        27,
	"Channel layout":                    28,
	"Sampling rate":                     29,
	"Frame rate mode":                   30,
	"Frame rate":                        31,
	"Standard":                          32,
	"Color space":                       32,
	"Chroma subsampling":                33,
	"Bit depth":                         34,
	"Scan type":                         35,
	"Scan order":                        35,
	"Compression mode":                  36,
	"Bits/(Pixel*Frame)":                37,
	"Time code of first frame":          38,
	"Time code source":                  39,
	"GOP, Open/Closed":                  40,
	"GOP, Open/Closed of first frame":   41,
	"Delay relative to video":           42,
	"Count of elements":                 42,
	"Stream size":                       43,
	"Source stream size":                43,
	"Title":                             44,
	"Language":                          44,
	"Service kind":                      45,
	"Writing library":                   46,
	"Encoding settings":                 47,
	"Default":                           48,
	"Forced":                            49,
	"Dialog Normalization":              50,
	"bsid":                              50,
	"dsurmod":                           50,
	"acmod":                             50,
	"lfeon":                             50,
	"compr":                             50,
	"dynrng":                            50,
	"cmixlev":                           50,
	"surmixlev":                         50,
	"mixlevel":                          50,
	"roomtyp":                           50,
	"dialnorm_Average":                  50,
	"dialnorm_Minimum":                  50,
	"dialnorm_Maximum":                  50,
	"dialnorm_Count":                    50,
	"compr_Average":                     50,
	"compr_Minimum":                     50,
	"compr_Maximum":                     50,
	"compr_Count":                       50,
	"dynrng_Average":                    50,
	"dynrng_Minimum":                    50,
	"dynrng_Maximum":                    50,
	"dynrng_Count":                      50,
	"Color range":                       51,
	"Color primaries":                   52,
	"Transfer characteristics":          53,
	"Matrix coefficients":               54,
	"Mastering display color primaries": 54,
	"Mastering display luminance":       54,
	"Maximum Content Light Level":       54,
	"Maximum Frame-Average Light Level": 54,
	"Alternate group":                   55,
	"Codec configuration box":           56,
	"List":                              57,
	"Service name":                      58,
	"Service provider":                  59,
	"Service type":                      60,
}
