package mediainfo

var generalFieldOrder = map[string]int{
	"ID":                    -2,
	"Unique ID":             -1,
	"Complete name":         0,
	"Format":                1,
	"Format/Info":           2,
	"Format settings":       3,
	"Format profile":        4,
	"Format version":        5,
	"Codec ID":              6,
	"File size":             7,
	"Duration":              8,
	"Overall bit rate mode": 9,
	"Overall bit rate":      10,
	"Frame rate":            11,
	"Writing application":   12,
	"Writing library":       13,
	"ErrorDetectionType":    14,
}

var streamFieldOrder = map[string]int{
	"ID":                                0,
	"Menu ID":                           1,
	"Format":                            2,
	"Format/Info":                       3,
	"Format version":                    4,
	"Muxing mode":                       5,
	"Format profile":                    6,
	"Format settings":                   7,
	"Format settings, BVOP":             8,
	"Format settings, QPel":             9,
	"Format settings, GMC":              10,
	"Format settings, Matrix":           11,
	"Format settings, GOP":              12,
	"Format settings, CABAC":            13,
	"Format settings, Reference frames": 14,
	"Codec ID":                          15,
	"Codec ID/Info":                     16,
	"Duration":                          17,
	"Source duration":                   18,
	"Source_Duration_LastFrame":         19,
	"Bit rate mode":                     20,
	"Bit rate":                          21,
	"Nominal bit rate":                  22,
	"Maximum bit rate":                  23,
	"Width":                             24,
	"Height":                            25,
	"Display aspect ratio":              26,
	"Channel(s)":                        27,
	"Channel layout":                    28,
	"Sampling rate":                     29,
	"Frame rate mode":                   30,
	"Frame rate":                        31,
	"Color space":                       32,
	"Chroma subsampling":                33,
	"Bit depth":                         34,
	"Scan type":                         35,
	"Compression mode":                  36,
	"Bits/(Pixel*Frame)":                37,
	"Time code of first frame":          38,
	"Time code source":                  39,
	"GOP, Open/Closed":                  40,
	"GOP, Open/Closed of first frame":   41,
	"Delay relative to video":           42,
	"Stream size":                       43,
	"Source stream size":                44,
	"Writing library":                   45,
	"Encoding settings":                 46,
	"Default":                           47,
	"Forced":                            48,
	"Color range":                       49,
	"Alternate group":                   50,
	"Codec configuration box":           51,
	"List":                              52,
	"Service name":                      53,
	"Service provider":                  54,
	"Service type":                      55,
}
